### ISSUE TITLE
the link to your blog post no longer working!

### ISSUE THREAD

**Issue by tomjuggler** [TKJElectronics/ATtinyRemote#1]
Hi, I recently found your blog post and after purchasing all the parts (crystal attiny's etc) to try and follow along the link is down! http://blog.tkjelectronics.dk/2012/03/attinyremote/

Just thought I would let you know, I will keep trying, haven't found anything nearly as comprehensive as your post yet.

**Comment by Lauszus** [comment]
Thanks, we already know and are working on it. Our site were attacked by a malware script not so long ago and we are still working on getting the full site back up.

For now you can use Google cache to view the page.

Sorry for the inconvenience.
